services:
 redis:
  image: redis
  container_name: lab-order-ftp-redis
  restart: always
  ports:
    - '6379:6379'
  command: redis-server --save 20 1 --loglevel warning --requirepass laborderpassword
  networks: 
    - 'test'

 server:
  build: "./"
  container_name: lab-order-ftp-server
  restart: always
  env_file: 
    - './.env'
  ports: 
    - '4553:4553'
  depends_on: 
    - redis
  networks: 
    - 'test'

networks:
  test:

